AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.0
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Style/AsciiComments:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
      inject: 'inject'

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - spec/**/*_spec.rb

Style/BracesAroundHashParameters:
  Exclude:
    - spec/**/*_spec.rb

Style/FormatString:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/RedundantSelf:
  Enabled: false

Layout/AlignHash:
  Enabled: true
  EnforcedLastArgumentHashStyle: always_ignore

Style/TrivialAccessors:
  AllowPredicates: true

#################### Metrics ###############################

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

#################### Lint ##################################

Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Lint/Debugger:
  Enabled: true

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

#################### Performance ###########################

Performance/Casecmp:
  Enabled: true

Performance/CaseWhenSplat:
  Enabled: true

Performance/DoubleStartEndWith:
  IncludeActiveSupportAliases: true

Performance/EndWith:
  Enabled: true

Performance/FixedSize:
  Enabled: true

Performance/FlatMap:
  Enabled: true

Performance/HashEachMethods:
  Enabled: true

Performance/LstripRstrip:
  Enabled: true

Performance/RangeInclude:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/RedundantSortBy:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/Sample:
  Enabled: true

Performance/Size:
  Enabled: true

Performance/CompareWithBlock:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/TimesMap:
  Enabled: true

#################### Bundler ###############################

Rails:
  Enabled: true

Rails/ActionFilter:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: true

Rails/ActiveSupportAliases:
  Enabled: true

Rails/Blank:
  Enabled: true

Rails/Date:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/DelegateAllowBlank:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: true

Rails/EnumUniqueness:
  Enabled: true

Rails/Exit:
  Enabled: true

Rails/FilePath:
  Enabled: true

Rails/FindBy:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: true

Rails/NotNullColumn:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/PluralizationGrammar:
  Enabled: true

Rails/Present:
  Enabled: true

Rails/ReadWriteAttribute:
  Enabled: true

Rails/RelativeDateConstant:
  Enabled: true

Rails/RequestReferer:
  Enabled: true

Rails/ReversibleMigration:
  Enabled: true

Rails/SafeNavigation:
  Enabled: true

Rails/ScopeArgs:
  Enabled: true

Rails/TimeZone:
  Enabled: true

Rails/UniqBeforePluck:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

Rails/Validation:
  Enabled: true

#################### Security ##############################

Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/YAMLLoad:
  Enabled: true

#################### Bundler ###############################

Bundler/DuplicatedGem:
  Description: 'Checks for duplicate gem entries in Gemfile.'
  Enabled: true
  Include:
    - '**/Gemfile'
    - '**/gems.rb'

Bundler/OrderedGems:
  Description: >-
                 Gems within groups in the Gemfile should be alphabetically sorted.
  Enabled: true
  Include:
    - '**/Gemfile'
    - '**/gems.rb'
